// Generated by Wrangler on Mon Apr 29 2024 07:38:32 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV_CACHE: KVNamespace;
	AUTH_SECRET: string;
	DISCORD_ID: string;
	DISCORD_SECRET: string;
	DISCORD_BOT_TOKEN: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	WAKATIME_SECRET_API_KEY: string;
	STEAMGRIDDB_API_KEY: string;
	STEAM_API_KEY: string;
	D1_DATABASE: D1Database;
}
