// Generated by Wrangler on Sun Apr 28 2024 23:48:45 GMT+0700 (Indochina Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	DISCORD_ID: string;
	DISCORD_SECRET: string;
	DISCORD_BOT_TOKEN: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	WAKATIME_SECRET_API_KEY: string;
	STEAMGRIDDB_API_KEY: string;
	STEAM_API_KEY: string;
}
