import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { GeistSans } from "geist/font/sans";

import "./globals.scss";

import { cn } from "~/lib/utils";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn("container flex flex-col", GeistSans.className)}>
        <header className="bg-[#ff0]">navbr</header>
        <main className={cn("bg-[#f00]", styles.layout_container)}>
          {children}
        </main>
      </body>
    </html>
  );
}
