import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { GeistSans } from "geist/font/sans";

import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/providers/theme-provider";
import Borders from "./_components/borders";
import Navbar from "./_components/navbar";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "container relative flex flex-col overflow-x-hidden",
          GeistSans.className,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="mb-16 flex flex-col px-4 md:mx-6">{children}</main>
          <Borders />
        </ThemeProvider>
      </body>
    </html>
  );
}
