import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { GeistSans } from "geist/font/sans";

import Navbar from "./_components/navbar";

import "./globals.scss";

import { cn } from "~/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn("container flex flex-col", GeistSans.className)}>
        <Navbar />
        <main className={cn("mb-16 flex flex-col bg-[#f00] px-4 md:mx-6")}>
          {children}
        </main>
      </body>
    </html>
  );
}
